apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.confName }}
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen {{ .Values.port }};
        location / {
          root /usr/share/nginx/html;
          index index.html;
          auth_basic "Restricted Content";
          auth_basic_user_file /etc/nginx/secrets/.htpasswd;
        }
      }
    }