apiVersion: v1
kind: ConfigMap
metadata:
  name: html-config
  namespace: nginx-app
data:
  index.html: |
    <html>
    <body>
      <h1>Hello World!</h1>
      <p>hello hello</p>
    </body>
    </html>