api:
  name: payment-api
  replicaCount: 2
  maxReplicas: 5
  minReplicas: 2
  image:
    repository: "858986858999.dkr.ecr.eu-central-1.amazonaws.com/payment-api-pt3"
    tag: "1.27.0-alpine"
  service:
    port: 8080
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"

worker:
  name: payment-worker
  replicaCount: 1
  minReplicas: 1
  maxReplicas: 3
  image:
    repository: "858986858999.dkr.ecr.eu-central-1.amazonaws.com/payment-worker-pt3"
    tag: "1.27.0-alpine"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"

ingress:
  name: payment-ingress
  enabled: true 
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
