api:
  name: payment-api
  replicaCount: 2
  maxReplicas: 5
  minReplicas: 2
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  startupProbe:
    failureThreshold: 12
    periodSeconds: 10
  livenessProbe:
    periodSeconds: 10
  readinessProbe:
    periodSeconds: 10    
  image:
    repository: "858986858999.dkr.ecr.eu-central-1.amazonaws.com/payment-api-pt3"
    tag: "1.27.0-alpine"
  service:
    port: 8080
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"

worker:
  name: payment-worker
  replicaCount: 1
  minReplicas: 1
  maxReplicas: 3
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  startupProbe:
    failureThreshold: 12
    periodSeconds: 10
  livenessProbe:
    periodSeconds: 10
  readinessProbe:
    periodSeconds: 10
  service:
    port: 8090
  image:
    repository: "858986858999.dkr.ecr.eu-central-1.amazonaws.com/payment-worker-pt3"
    tag: "1.27.0-alpine"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"

ingress:
  name: payment-ingress
  enabled: true 
  className: "alb"
  path: /*
  pathType: Prefix
  port: 
    number: 80
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
