apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-html-config
  namespace: {{ .Values.namespace }}
data:
  index.html: |
    <html>
    <body>
      <h1>Hello World!</h1>
      <p>hello hello</p>
    </body>
    </html>