name: "Terraform pipeline"

on:
  push:
    branches: [ '**' ]
    paths:
      - '07-ECS-app-pt3/**'                       
      - '!07-ECS-app-pt3/modules/app/**'          
      - '.github/workflows/02-terraform-infra.yml'

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true 

jobs:
  plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_PLAN }}
          aws-region: eu-central-1

      - uses: hashicorp/setup-terraform@v3

      - name: Init & Plan
        run: |
          cd 07-ECS-app-pt3/envs/dev
          terraform init
          terraform plan -out=tfplan -input=false -var="image_tag=latest"

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-artifact
          path: 07-ECS-app-pt3/envs/dev/tfplan

  apply:
    name: "Terraform Apply"
    needs: plan
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_APPLY }}
          aws-region: eu-central-1

      - uses: hashicorp/setup-terraform@v3

      - name: Init
        run: |
          cd 07-ECS-app-pt3/envs/dev
          terraform init

      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan-artifact
          path: 07-ECS-app-pt3/envs/dev

      - name: Apply
        run: |
          cd 07-ECS-app-pt3/envs/dev
          terraform apply -auto-approve tfplan