name: "ECS-app-pt3 Pipeline"

on:
  push:
    branches: [ '**' ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  # Docker & ECR
  prepare-and-docker:
    name: "Bootstrap & Docker"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./envs/dev
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_APPLY }}
          aws-region: eu-central-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init & Format Check
        run: |
          terraform init
          terraform fmt -check
          terraform validate

      - name: Create ECR Repo Only
        run: terraform apply -target=module.ecr -var="image_tag=bootstrap" -auto-approve

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ecs-app-pt3-ecr-repo
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd ../..
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./modules/app
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  # Plan
  terraform-plan:
    name: "Terraform Plan"
    needs: prepare-and-docker
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./envs/dev
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_PLAN }}
          aws-region: eu-central-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        env:
          TF_VAR_image_tag: ${{ github.sha }}
        run: terraform plan -out=tfplan -input=false

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ./envs/dev/tfplan

  # Apply
  terraform-apply:
    name: "Terraform Apply"
    needs: terraform-plan
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: ./envs/dev
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_APPLY }}
          aws-region: eu-central-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ./envs/dev

      - name: Terraform Apply
        env:
          TF_VAR_image_tag: ${{ github.sha }}
        run: terraform apply -auto-approve tfplan