name: Build, Scan & Push (Payment-App)

on:
  push:
    branches: [ "**" ]
    paths:
      - '20-k8s-payment-app-pt1/**'
      - '.github/workflows/**'
      - '!20-k8s-payment-app-pt1/infrastructure/**'
      - '!20-k8s-payment-app-pt1/infrastructure/unused/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-central-1
  AWS_ROLE_ARN: "arn:aws:iam::858986858999:role/GitHubActions-Apply" 
  BASE_PATH: ./20-k8s-payment-app-pt1

jobs:
  build-scan-push:
    name: Build & Scan ${{ matrix.app }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - app: payment-api
            ecr_repo: payment-api-prod
          - app: payment-worker
            ecr_repo: payment-worker-prod

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/${{ matrix.ecr_repo }}:$IMAGE_TAG \
                       -t $ECR_REGISTRY/${{ matrix.ecr_repo }}:latest \
                       $BASE_PATH/${{ matrix.app }}

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.login-ecr.outputs.registry }}/${{ matrix.ecr_repo }}:${{ github.sha }}
          format: 'table'
          exit-code: '1'     
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL' 
          timeout: '15m'

      - name: Push to ECR
        if: success()
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push $ECR_REGISTRY/${{ matrix.ecr_repo }}:$IMAGE_TAG
          docker push $ECR_REGISTRY/${{ matrix.ecr_repo }}:latest